<?php

/**
 * @file
 * Contains aping.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function aping_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the aping module.
    case 'help.page.aping':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('apiNG implementation for Drupal') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function aping_theme() {
  $theme['social_wall'] = [
    'variables' => ['name' => NULL],
    'template' => 'social-wall',
  ];
  return $theme;
}

// Store relative path to the module in a variable used in social-wall.html.twig.
function aping_preprocess_social_wall(&$variables) {
  $variables['modulepath'] = drupal_get_path('module', 'aping');
}
